### PR TITLE
Added hatchet Gem and some basic JVM tests

### PR DESCRIPTION
**Pull request by jkutner**

### CODE REVIEW

**Comment by freeformz** [comment]
Again, I think all of this should be in the Java buildpack(s), not this one. IMO this buildpack should only be used to setup the metrics agent.

**Comment by jkutner** [comment]
@freeformz eventually yea. But i need to make changes to this buildpack in the short-term, and I need tests for it to do that with confidence.

**Comment by freeformz** [comment]
So why not move this stuff into the other buildpack(s) and do the tests there?

It seems like accreting additional detections here just solidifies the inertia of using this buildpack.

Otherwise 👍

**Comment by freeformz** [comment]
FWIW: I'd much rather not use hatchet and instead use shunit along with docker. But otherwise 👍

**Review by apg — APPROVED** [review]
This seems like a win.

We should add the Ruby Getting Started app to this as well, though.

@schneems would you be interested in doing the work for that? Not sure how we can inject barnes easily into the checked out getting started app, which seems like the only potential gotcha.

**Comment by freeformz** [comment]
@apg Why would the detection / injection logic not be in the language buildpack?

**Comment by apg** [comment]
@freeformz raises great concerns that I, as a non-buildpack maintainer, have no real opinions on. The choice of testing framework does not impact the rest of the buildpacks' functionality, which I also agree is getting to be out of hand. However, it's what we've got, at the moment, so until we can schedule work to actively go about getting it into an ideal state...

**Comment by apg** [comment]
@freeformz I think as much as possible *should* be in the language buildpack, and we did ourselves a disservice by GA'ing with it *not* that way.

All that being said, I think it's likely the case that the .profile.d script *has* to have some detection in it, so we possibly at this time can't eliminate all detection from this.

Whether or not it matters that the .profile.d script has detection is probably moot though anyway.

**Comment by schneems** [comment]
> Not sure how we can inject barnes easily into the checked out getting started app

It's not the easiest, but maybe it's not that bad either. I think it would be something like:

```
runner = Hatchet::Runner.new("getting_started").setup!
runner.in_directory do
  File.open("Gemfile", "a") {|f| f.puts "gem 'barnes'" }
  ` bundle install`
end
runner.deploy
```

You might want to do something like this to actually make sure the app boots without error:

```
runner.deploy do |app|
  assert_match "hello world", app.run "rails runner 'puts %Q{hello world}'"
end
```

Though this alone wouldn't tell us if metrics are working or not just that nothing crashed. What kind of functionally were you thinking of testing?

**Comment by jkutner** [comment]
@schneems i was mostly interested in making sure I didn't crash an app by adding the metrics buildpack. I also think you could create a branch on the getting-started app with the barnes Gem to make things simpler. It might become stale, but it'sa quick thing.

**Pull request merged**
